# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AppName_config = debug

else ifeq ($(config),release)
  AppName_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := AppName

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AppName:
ifneq (,$(AppName_config))
	@echo "==== Building AppName ($(AppName_config)) ===="
	@${MAKE} --no-print-directory -C AppName -f Makefile config=$(AppName_config)
endif

clean:
	@${MAKE} --no-print-directory -C AppName -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AppName"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"